# Generated by Django 4.2.2 on 2024-03-07 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credent',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
    ]
