# Generated by Django 4.2.2 on 2024-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('TR_NO', models.IntegerField()),
                ('TIME', models.TimeField()),
                ('VOLTAGE', models.DecimalField(decimal_places=2, max_digits=6)),
                ('AMP', models.DecimalField(decimal_places=2, max_digits=6)),
                ('KWH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('O_L', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Sixth_FLOOR_CS', models.DecimalField(decimal_places=2, max_digits=6)),
                ('PROFESSOR_QUATERS', models.DecimalField(decimal_places=2, max_digits=6)),
                ('HOSTEL_N_ROAD_SIDE', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lc_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lc_2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'elecread',
            },
        ),
    ]
