# Generated by Django 4.2.2 on 2024-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_electric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric',
            name='TIME',
            field=models.CharField(max_length=5),
        ),
    ]
