# Generated by Django 5.0.7 on 2024-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_electric_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electric',
        ),
    ]
